nodeLinker: node-modules

packageExtensions:
  '@chromatic-com/storybook@*':
    dependencies:
      'react': '^18.0.0'
  '@storybook/addon-webpack5-compiler-swc@*':
    dependencies:
      'webpack': '>=2'
  'react-confetti@*':
    dependencies:
      'react': '^18.0.0'
