nodeLinker: node-modules

packageExtensions:
  '@chromatic-com/storybook@*':
    dependencies:
      'react': '^18.0.0'
  '@storybook/addon-webpack5-compiler-swc@*':
    dependencies:
      'webpack': '>=2'
  'react-confetti@*':
    dependencies:
      'react': '^18.0.0'
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
      'typescript': '>=4'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
